### ISSUE TITLE
AttributeError: 'numpy.random._generator.Generator' object has no attribute 'randn'

### ISSUE THREAD

**Issue by Ruebin** [eleurent/highway-env#379]
There are some errors for env like  roundabout-v0 parking-v0 intersection-v0 racetrack-v0 but highway-v0 merge-v0 is ok?

Traceback (most recent call last):
  File ".\Road.py", line 13, in <module>
    env = Road('roundabout-v0').bulid()
  File ".\Road.py", line 9, in bulid
    return gym.make(self.type)
  File "E:\Anaconda3\envs\AD\lib\site-packages\gym\envs\registration.py", line 640, in make
    env = env_creator(**_kwargs)
  File "E:\Anaconda3\envs\AD\lib\site-packages\highway_env\envs\common\abstract.py", line 71, in __init__
    self.reset()
  File "E:\Anaconda3\envs\AD\lib\site-packages\highway_env\envs\common\abstract.py", line 190, in reset
    self._reset()
  File "E:\Anaconda3\envs\AD\lib\site-packages\highway_env\envs\roundabout_env.py", line 58, in _reset
    self._make_vehicles()
  File "E:\Anaconda3\envs\AD\lib\site-packages\highway_env\envs\roundabout_env.py", line 154, in _make_vehicles
    longitudinal=5 + self.np_random.randn()*position_deviation,
AttributeError: 'numpy.random._generator.Generator' object has no attribute 'randn'

**Comment by eleurent** [comment]
Hello, 
This has been fixed on the development version (see https://github.com/eleurent/highway-env/commit/1d2f281ef0f970afb380b15dbec9da40cc0ba432).
Alternatively, if you use the stable version of highway-env, you can probably install a previous version of numpy before this was deprecated.
