### ISSUE TITLE
"Training an agent" example

### ISSUE THREAD

**Issue by smarianimore** [eleurent/highway-env#409]
Hy everybody, 
I am trying to run the example code provided [here](https://highway-env.readthedocs.io/en/latest/quickstart.html#training-an-agent), but I get 2 errors depending on which version of gym(nasium) I install

If I run the code with gym 0.21 installed (automatically pulled as dependency while installing stable-baselines3, which is required by the example code), I got error

```

Traceback (most recent call last):
  File "/Users/sm/PycharmProjects/RomoliGiacomo/highway-env-venv/lib/python3.9/site-packages/gym/envs/registration.py", line 158, in spec
    return self.env_specs[id]
KeyError: 'highway-v0'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/sm/PycharmProjects/RomoliGiacomo/training.py", line 6, in <module>
    env = gym.make("highway-v0")
  File "/Users/sm/PycharmProjects/RomoliGiacomo/highway-env-venv/lib/python3.9/site-packages/gym/envs/registration.py", line 235, in make
    return registry.make(id, **kwargs)
  File "/Users/sm/PycharmProjects/RomoliGiacomo/highway-env-venv/lib/python3.9/site-packages/gym/envs/registration.py", line 128, in make
    spec = self.spec(path)
  File "/Users/sm/PycharmProjects/RomoliGiacomo/highway-env-venv/lib/python3.9/site-packages/gym/envs/registration.py", line 185, in spec
    raise error.DeprecatedEnv(
gym.error.DeprecatedEnv: Env highway-v0 not found (valid versions include ['__root__/highway-v0'])
```

I tried changing environment to any other listed in the documentation but the error stays the same

If I try to run the code with gym==0.26.2 installed (automatically pulled as dependency while installing highway-env) the following happens instead:

```
/Users/sm/PycharmProjects/RomoliGiacomo/highway-env-venv/lib/python3.9/site-packages/gym/utils/passive_env_checker.py:31: UserWarning: WARN: A Box observation space has an unconventional shape (neither an image, nor a 1D vector). We recommend flattening the observation to have only a 1D vector or use a custom policy to properly process the data. Actual observation shape: (5, 5)
  logger.warn(
Using cpu device
Wrapping the env with a `Monitor` wrapper
Wrapping the env in a DummyVecEnv.
Traceback (most recent call last):
  File "/Users/sm/PycharmProjects/RomoliGiacomo/training.py", line 19, in <module>
    model.learn(int(2e4))
  File "/Users/sm/PycharmProjects/RomoliGiacomo/highway-env-venv/lib/python3.9/site-packages/stable_baselines3/dqn/dqn.py", line 265, in learn
    return super().learn(
  File "/Users/sm/PycharmProjects/RomoliGiacomo/highway-env-venv/lib/python3.9/site-packages/stable_baselines3/common/off_policy_algorithm.py", line 323, in learn
    total_timesteps, callback = self._setup_learn(
  File "/Users/sm/PycharmProjects/RomoliGiacomo/highway-env-venv/lib/python3.9/site-packages/stable_baselines3/common/off_policy_algorithm.py", line 305, in _setup_learn
    return super()._setup_learn(
  File "/Users/sm/PycharmProjects/RomoliGiacomo/highway-env-venv/lib/python3.9/site-packages/stable_baselines3/common/base_class.py", line 408, in _setup_learn
    self._last_obs = self.env.reset()  # pytype: disable=annotation-type-mismatch
  File "/Users/sm/PycharmProjects/RomoliGiacomo/highway-env-venv/lib/python3.9/site-packages/stable_baselines3/common/vec_env/dummy_vec_env.py", line 75, in reset
    self._save_obs(env_idx, obs)
  File "/Users/sm/PycharmProjects/RomoliGiacomo/highway-env-venv/lib/python3.9/site-packages/stable_baselines3/common/vec_env/dummy_vec_env.py", line 105, in _save_obs
    self.buf_obs[key][env_idx] = obs
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.
```

Are both due to the API changes introduced by Gymnasium that are not yet assorbed by stable-baselines3?

**Comment by VanillaWhey** [comment]
For gym v0.21, you can use the version 1.6 of  highway-env. I think the second error is because SB3 does not support Gymnasium/Gym v0.26 yet.

**Comment by lukas0516** [comment]
Hello, I also encountered the same problem. I want to ask if you have solved this and how? Best @smarianimore

**Comment by smarianimore** [comment]
> For gym v0.21, you can use the version 1.6 of highway-env. I think the second error is because SB3 does not support Gymnasium/Gym v0.26 yet.

Are you @VanillaWhey  sure?
Pip prompt tells me 1.6 requires 0.25+:

```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
highway-env 1.6 requires gym>=0.25, but you have gym 0.21.0 which is incompatible.
```

**Comment by smarianimore** [comment]
@VanillaWhey nevermind, it works anyway for some weird reason XD
Thanks for the support

**Comment by eleurent** [comment]
> Pip prompt tells me 1.6 requires 0.25+:

That is correct

>  I think the second error is because SB3 does not support Gymnasium/Gym v0.26 yet.

That is also correct.

So until SB3 adds support gym 0.26 ([pending PR](https://github.com/DLR-RM/stable-baselines3/pull/780)), you have to use the supported gym==0.21 instead, which means that you must also downgrade highway-env to the last version that supported gym 0.21, which I believe was v1.6.

**Comment by smarianimore** [comment]
Dear @eleurent , 
I'm following up with a new error as it is raised by the same example, but if you prefer another issue just let me know.

I managed to let the code run, but now I get the following when training is finished:

```
Traceback (most recent call last):
  File "/Users/sm/PycharmProjects/RomoliGiacomo/training.py", line 30, in <module>
    obs, reward, done, truncated, info = env.step(action)
  File "/Users/sm/PycharmProjects/RomoliGiacomo/highway-env-venv/lib/python3.9/site-packages/gym/wrappers/order_enforcing.py", line 11, in step
    observation, reward, done, info = self.env.step(action)
  File "/Users/sm/PycharmProjects/RomoliGiacomo/highway-env-venv/lib/python3.9/site-packages/highway_env/envs/common/abstract.py", line 216, in step
    self._simulate(action)
  File "/Users/sm/PycharmProjects/RomoliGiacomo/highway-env-venv/lib/python3.9/site-packages/highway_env/envs/common/abstract.py", line 233, in _simulate
    self.action_type.act(action)
  File "/Users/sm/PycharmProjects/RomoliGiacomo/highway-env-venv/lib/python3.9/site-packages/highway_env/envs/common/action.py", line 240, in act
    self.controlled_vehicle.act(self.actions[action])
TypeError: unhashable type: 'numpy.ndarray'
```

**Comment by araffin** [comment]
> So until SB3 adds support gym 0.26 (https://github.com/DLR-RM/stable-baselines3/pull/780), you have to use the supported gym==0.21 instead,

you can already use this PR if needed (instructions are in the PR), you don't have to wait for the release (even though a beta version should be out in some weeks).

**Comment by eleurent** [comment]
Ah that's good to know, thanks @araffin !

**Comment by eleurent** [comment]
Ah that's good to know, thanks @araffin !

**Comment by eleurent** [comment]
@smarianimore hmmm, sb3's policy probably returns a numpy array (shape 1 or 0) where highway-env expects an int. in your training.py script you can just cast the action to int before calling env.step. But I'll also fix highway-env so it supports numpy types for discrete actions.

**Comment by smarianimore** [comment]
Dear @eleurent many thanks, any update on this?

**Comment by eleurent** [comment]
I guess not since the SB3's migration PR is still not merged, but you can still use that PR directly along with the latest highway-env release.

**Comment by eleurent** [comment]
(the `TypeError: unhashable type: 'numpy.ndarray'` mentionned above should be fixed at HEAD, I'll publish a new release soon)
