### ISSUE TITLE
Observation space contains redundant rewards information and cause flatten observation failure

### ISSUE THREAD

**Issue by PatrickYanZ** [eleurent/highway-env#412]
Hi I have an compilation error for observation space

```
PS I:\Research\tcom paper\MO-Gymnasium\tests> & D:/Users/yanzi/miniconda3/python.exe .\test_highway.py
observation_type
<highway_env.envs.common.observation.KinematicObservation object at 0x000002C266C0A730>
observation_space
Box(-inf, inf, (5, 5), float32)
<class 'gymnasium.spaces.box.Box'>
[[ 1.          0.7800287   0.          0.3125      0.        ]
 [ 1.          0.11869543  0.33333334 -0.01511534  0.        ]
 [ 1.          0.24316713  0.         -0.04433119  0.        ]
 [ 1.          0.36513504  0.6666667  -0.03588466  0.        ]
 [ 1.          0.48781383  0.         -0.01851263  0.        ]] {'speed': 25, 'crashed': False, 'action': 0, 'rewards': {'collision_reward': 0.0, 'right_lane_reward': 0.0, 'high_speed_reward': 0.5, 'on_road_reward': 1.0}}
Traceback (most recent call last):
  File "I:\Research\tcom paper\MO-Gymnasium\tests\test_highway.py", line 40, in <module>
    wrapped_obs, wrapped_obs_info = wrapped_env.reset()
  File "D:\Users\yanzi\miniconda3\lib\site-packages\gymnasium\core.py", line 416, in reset
    return self.observation(obs), info
  File "D:\Users\yanzi\miniconda3\lib\site-packages\gymnasium\wrappers\flatten_observation.py", line 41, in observation
    return spaces.flatten(self.env.observation_space, observation)
  File "D:\Users\yanzi\miniconda3\lib\functools.py", line 877, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
  File "D:\Users\yanzi\miniconda3\lib\site-packages\gymnasium\spaces\utils.py", line 155, in flatten
    raise NotImplementedError(f"Unknown space: `{space}`")
NotImplementedError: Unknown space: `Box(-inf, inf, (5, 5), float32)`


```

The testing script is from https://github.com/Farama-Foundation/MO-Gymnasium/blob/main/mo_gymnasium/envs/highway/highway.py. I made a slightly change on this.

```
import gym
import gymnasium
import numpy as np
from gymnasium.spaces import (
    Box,
    Dict,
    Discrete,
    Graph,
    MultiBinary,
    MultiDiscrete,
    Sequence,
    Text,
    Tuple,
)

import gymnasium.spaces as spaces
import numpy as np
from gymnasium.spaces import Box
from gymnasium.spaces.utils import flatten_space, flatten
import gymnasium
import mo_gymnasium as mo_gym
from gymnasium import spaces
from gymnasium.wrappers import FlattenObservation

from highway_env.envs import HighwayEnv, HighwayEnvFast


class MOHighwayEnv(HighwayEnv):
    """
    ## Description
    Multi-objective version of the HighwayEnv environment.

    See [highway-env](https://github.com/eleurent/highway-env) for more information.

    ## Reward Space
    The reward is 3-dimensional:
    - 0: high speed reward
    - 1: right lane reward
    - 2: collision reward
    """

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.reward_space = gymnasium.spaces.Box(low=-1.0, high=1.0, shape=(3,), dtype=np.float32)
        self.observation_space = _convert_space(self.observation_space)
        self.action_space = _convert_space(self.action_space)

    def step(self, action):
        obs, reward, terminated, truncated, info = super().step(action)
        rewards = info["rewards"]
        vec_reward = np.array(
            [
                rewards["high_speed_reward"],
                rewards["right_lane_reward"],
                -rewards["collision_reward"],
            ],
            dtype=np.float32,
        )
        vec_reward *= rewards["on_road_reward"]
        info["original_reward"] = reward
        return obs, vec_reward, terminated, truncated, info


class MOHighwayEnvFast(HighwayEnvFast):
    """A multi-objective version of the HighwayFastEnv environment."""

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.reward_space = gymnasium.spaces.Box(low=-1.0, high=1.0, shape=(3,), dtype=np.float32)
        self.observation_space = _convert_space(self.observation_space)
        self.action_space = _convert_space(self.action_space)
        print('observation_type')
        print(self.observation_type)
        print('observation_space')
        print(self.observation_space)

        
        print(type(self.observation_space))

    def step(self, action):
        obs, reward, terminated, truncated, info = super().step(action)
        rewards = info["rewards"]
        vec_reward = np.array(
            [
                rewards["high_speed_reward"],
                rewards["right_lane_reward"],
                -rewards["collision_reward"],
            ],
            dtype=np.float32,
        )
        vec_reward *= rewards["on_road_reward"]
        info["original_reward"] = reward
        return obs, vec_reward, terminated, truncated, info


def _convert_space(space: gym.Space) -> gymnasium.Space:
    """Converts a gym space to a gymnasium space.
    Args:
        space: the space to convert
    Returns:
        The converted space
    """
    if isinstance(space, gym.spaces.Discrete):
        return gymnasium.spaces.Discrete(n=space.n)
    elif isinstance(space, gym.spaces.Box):
        return gymnasium.spaces.Box(low=space.low, high=space.high, shape=space.shape, dtype=space.dtype)
    elif isinstance(space, gym.spaces.MultiDiscrete):
        return MultiDiscrete(nvec=space.nvec)
    elif isinstance(space, gym.spaces.MultiBinary):
        return MultiBinary(n=space.n)
    elif isinstance(space, gym.spaces.Tuple):
        return Tuple(spaces=tuple(map(_convert_space, space.spaces)))
    elif isinstance(space, gym.spaces.Dict):
        return Dict(spaces={k: _convert_space(v) for k, v in space.spaces.items()})
    elif isinstance(space, gym.spaces.Sequence):
        return Sequence(space=_convert_space(space.feature_space))
    elif isinstance(space, gym.spaces.Graph):
        return Graph(
            node_space=_convert_space(space.node_space),  # type: ignore
            edge_space=_convert_space(space.edge_space),  # type: ignore
        )
    elif isinstance(space, gym.spaces.Text):
        return Text(
            max_length=space.max_length,
            min_length=space.min_length,
            charset=space._char_str,
        )
    else:
        raise NotImplementedError(f"Cannot convert space of type {space}. Please upgrade your code to gymnasium.")


```
Testing script is s 

```
import gymnasium.spaces as spaces
import numpy as np
from gymnasium.spaces import Box
from gymnasium.spaces.utils import flatten_space, flatten
import gymnasium
import mo_gymnasium as mo_gym
from gymnasium import spaces
from gymnasium.wrappers import FlattenObservation



env = mo_gym.make("mo-highway-fast-v0")
wrapped_env = FlattenObservation(env)
obs, info = env.reset()
print(obs,info)
wrapped_obs, wrapped_obs_info = wrapped_env.reset()
print(wrapped_obs, wrapped_obs_info)
```

I suspect once executing `self.observation_space`, the output is

```[[ 1.          0.7800287   0.          0.3125      0.        ]
 [ 1.          0.11869543  0.33333334 -0.01511534  0.        ]
 [ 1.          0.24316713  0.         -0.04433119  0.        ]
 [ 1.          0.36513504  0.6666667  -0.03588466  0.        ]
 [ 1.          0.48781383  0.         -0.01851263  0.        ]] {'speed': 25, 'crashed': False, 'action': 0, 'rewards': {'collision_reward': 0.0, 'right_lane_reward': 0.0, 'high_speed_reward': 0.5, 'on_road_reward': 1.0}}
```

However in Kinematics observation, the speed and rewards should not be included.
I believe the observation will be 
 ``` 
[[ 1.          0.7800287   0.          0.3125      0.        ]
 [ 1.          0.11869543  0.33333334 -0.01511534  0.        ]
 [ 1.          0.24316713  0.         -0.04433119  0.        ]
 [ 1.          0.36513504  0.6666667  -0.03588466  0.        ]
 [ 1.          0.48781383  0.         -0.01851263  0.        ]]
```
 
 That is I can flatten the observation to proceed the learning. 
 Also, I believe the Kinematic  `observation_space` may direct to `highway_env.envs.common.observation.KinematicObservation.space() `rather than others.
 
Appreciate it in advance

**Comment by eleurent** [comment]
Looks like you figured it out, let me know if you still have any issue :)
