### ISSUE TITLE
KeyError: 23， “self.env.step(action)”is wrong

### ISSUE THREAD

**Issue by shile1998** [eleurent/highway-env#416]
The self-written DQN algorithm reports an error "KeyError", the gym version is 0.21.0, and the highway version is 1.6

`Traceback (most recent call last):
  File "main.py", line 218, in <module>
    agent.train(n_episodes=opt.num_episodes, eps_decay=opt.eps_decay)

  File "/home/sl/iv_rl-master/dqn/dqn.py", line 192, in train
    self.test(episode=i_episode)

  File "/home/sl/iv_rl-master/dqn/dqn.py", line 213, in test
    next_state, reward, done, _ = self.env.step(action)

  File "/home/sl/anaconda3/envs/213/lib/python3.8/site-packages/gym/wrappers/order_enforcing.py", line 37, in step
    return self.env.step(action)

  File "/home/sl/anaconda3/envs/213/lib/python3.8/site-packages/gym/wrappers/env_checker.py", line 39, in step
    return self.env.step(action)

  File "/home/sl/anaconda3/envs/213/lib/python3.8/site-packages/highway_env/envs/common/abstract.py", line 216, in step
    self._simulate(action)

  File "/home/sl/anaconda3/envs/213/lib/python3.8/site-packages/highway_env/envs/common/abstract.py", line 233, in _simulate
    self.action_type.act(action)

  File "/home/sl/anaconda3/envs/213/lib/python3.8/site-packages/highway_env/envs/common/action.py", line 240, in act
    self.controlled_vehicle.act(self.actions[action])
KeyError: 23
`

**Comment by eleurent** [comment]
Hi, 
I don't know which DQN implementation you are using, but it seems to be returning an invalid action: 23.
When using discrete actions, the set of available actions is defined here:

https://github.com/eleurent/highway-env/blob/ffb35eacdfb2671623dc12d99b2ed5b6cb76e531/highway_env/envs/common/action.py#L183

and the maximum action is 4,which is why your action 23 is unavailable.
Your DQN implementation should read the number of actions available from the env's `action_space`.
