### ISSUE TITLE
Error importing highway_env

### ISSUE THREAD

**Issue by mac124** [eleurent/highway-env#59]
Hello,

I have tried installing with pip and pip3 as well. Using pip as follows:

pip install --user git+https://github.com/eleurent/highway-env gives following error message
>>> import highway_env
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/marco/.local/lib/python2.7/site-packages/highway_env/__init__.py", line 2, in <module>
    import highway_env.envs
  File "/home/marco/.local/lib/python2.7/site-packages/highway_env/envs/__init__.py", line 1, in <module>
    from highway_env.envs.highway_env import *
  File "/home/marco/.local/lib/python2.7/site-packages/highway_env/envs/highway_env.py", line 3, in <module>
    from highway_env import utils
ImportError: cannot import name utils

if I install using pip3 with the following
pip3 install --user git+https://github.com/eleurent/highway-env I get the following error message
>>> import highway_env
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/marco/.local/lib/python3.6/site-packages/highway_env/__init__.py", line 2, in <module>
    import highway_env.envs
  File "/home/marco/.local/lib/python3.6/site-packages/highway_env/envs/__init__.py", line 1, in <module>
    from highway_env.envs.highway_env import *
  File "/home/marco/.local/lib/python3.6/site-packages/highway_env/envs/highway_env.py", line 4, in <module>
    from highway_env.envs.common.abstract import AbstractEnv
  File "/home/marco/.local/lib/python3.6/site-packages/highway_env/envs/common/abstract.py", line 8, in <module>
    from highway_env.envs.common.observation import observation_factory
  File "/home/marco/.local/lib/python3.6/site-packages/highway_env/envs/common/observation.py", line 7, in <module>
    from highway_env.road.lane import AbstractLane
  File "/home/marco/.local/lib/python3.6/site-packages/highway_env/road/lane.py", line 5, in <module>
    from highway_env.vehicle.kinematics import Vehicle
  File "/home/marco/.local/lib/python3.6/site-packages/highway_env/vehicle/kinematics.py", line 9, in <module>
    from highway_env.road.road import Road, LaneIndex
  File "/home/marco/.local/lib/python3.6/site-packages/highway_env/road/road.py", line 7, in <module>
    from highway_env.road.lane import LineType, StraightLane
ImportError: cannot import name 'LineType'

Thank you for the help!

**Comment by aseembehl** [comment]
Yes same error for me

**Comment by eleurent** [comment]
It should be fixed now @mac124 @aseembehl , sorry about that.

Note that only Python 3 is supported.

**Comment by qianyeshuilong** [comment]
Hello, 
I'm sorry to bother you.
