### ISSUE TITLE
Question about Observations 

### ISSUE THREAD

**Issue by Cuizy-faiz** [eleurent/highway-env#85]
Can you give some details about Observation？In your user guide，the content about observation is empty. When I read the value of Observation，I don't know which element corresponds to which car。

**Comment by eleurent** [comment]
Hi @Cuizy-faiz 
I am currently writing the documentation (see #62), I'll update the Observation section and get back to you once I'm done if you have any question left.

**Comment by Cuizy-faiz** [comment]
How to get the speed information in Grayscale Image observation?

**Comment by eleurent** [comment]
The speed information is indirectly present, since the observation a stack of the last four frames.

**Comment by Cuizy-faiz** [comment]
I set the observation type=‘’GrayscaleObservation‘’，but the pycharm give the error as follow：
Traceback (most recent call last):
  File "C:/myexp/exp_1.py", line 4, in <module>
    env = gym.make("highway-v0")
  File "C:\data_science\envs\deeplearning\lib\site-packages\gym\envs\registration.py", line 145, in make
    return registry.make(id, **kwargs)
  File "C:\data_science\envs\deeplearning\lib\site-packages\gym\envs\registration.py", line 90, in make
    env = spec.make(**kwargs)
  File "C:\data_science\envs\deeplearning\lib\site-packages\gym\envs\registration.py", line 60, in make
    env = cls(**_kwargs)
  File "C:\data_science\envs\deeplearning\lib\site-packages\highway_env-1.0.dev0-py3.6.egg\highway_env\envs\common\abstract.py", line 56, in __init__
  File "C:\data_science\envs\deeplearning\lib\site-packages\highway_env-1.0.dev0-py3.6.egg\highway_env\envs\common\abstract.py", line 109, in define_spaces
  File "C:\data_science\envs\deeplearning\lib\site-packages\highway_env-1.0.dev0-py3.6.egg\highway_env\envs\common\observation.py", line 332, in observation_factory
  File "C:\data_science\envs\deeplearning\lib\site-packages\highway_env-1.0.dev0-py3.6.egg\highway_env\envs\common\observation.py", line 48, in __init__
KeyError: 'observation_shape'

what‘s the key of GrayscaleObservation type?

**Comment by eleurent** [comment]
You should set the `"observation_shape"` key in the observation configuration to be the same as the `"screen_width"`, `"screen_height"` environment configurations.
See the [documentation example](https://highway-env.readthedocs.io/en/latest/observations/index.html#grayscale-example-configuration)

**Comment by Cuizy-faiz** [comment]
I set the configuration as documentation example， but when I print the obs，the observation type is still the kinematic type. the code is as follows:

import gym
import highway_env

env = gym.make("highway-v0")
done = False
screen_width, screen_height = 128, 128
config = {
    "offscreen_rendering": False,
    "observation": {
        "type": "GrayscaleObservation",
        "weights": [0.2989, 0.5870, 0.1140],  # weights for RGB conversion
        "stack_size": 4,
        "observation_shape": (screen_width, screen_height)
    },
    "screen_width": screen_width,
    "screen_height": screen_height,
    "scaling": 1.75,
    "policy_frequency": 2
}
env.configure(config)

while not done:
    action = env.action_type.actions_indexes["IDLE"]
    obs, reward, done, info = env.step(action)
    print(obs)
    env.render()

**Comment by eleurent** [comment]
You have to `reset()` the environment after changing the configuration.
I will should that clarification to the documentation!

**Comment by Cuizy-faiz** [comment]
Can you give some details about the reward？like formula

**Comment by eleurent** [comment]
https://github.com/eleurent/highway-env/commit/14b1a8d63879d5b66b48f951bed84cdc31ea3394

**Comment by eleurent** [comment]
The documentation about observations have been filled, thus I am closing this issue. Feel free to reopen if contents are missing.
