### ISSUE TITLE
Having problems to run the code

### ISSUE THREAD

**Issue by narutoten520** [eleurent/highway-env#87]
@eleurent Hi eleurent, I am very interested in your work. Since I am a beginner of Python, I have some problems to run this toolbox. Hope you can help me! Thanks in advance.

When I run this line in the terminal "python experiments.py evaluate configs/CartPoleEnv/env.json configs/CartPoleEnv/DQNAgent.json --train --episodes=200", the problem is:

(base) C:\Users\user1\RL\scripts>python experiments.py evaluate configs/CartPoleEnv/env.json configs/CartPoleEnv/DQNAgent.json --train --episodes=200

INFO: Making new env: CartPole-v0
[INFO] This environment does not support configuration. 'CartPoleEnv' object has no attribute 'configure'
Traceback (most recent call last):
  File "experiments.py", line 148, in <module>
    main()
  File "experiments.py", line 43, in main
    evaluate(opts['<environment>'], opts['<agent>'], opts)
  File "experiments.py", line 60, in evaluate
    agent = load_agent(agent_config, env)
  File "C:\Users\user1\AppData\Roaming\Python\Python37\site-packages\rl_agents\agents\common\factory.py", line 41, in load_agent
    return agent_factory(env, agent_config)
  File "C:\Users\user1\AppData\Roaming\Python\Python37\site-packages\rl_agents\agents\common\factory.py", line 24, in agent_factory
    agent = agent_class(environment, config)
  File "C:\Users\user1\AppData\Roaming\Python\Python37\site-packages\rl_agents\agents\deep_q_network\pytorch.py", line 22, in __init__
    self.device = choose_device(self.config["device"])
  File "C:\Users\user1\AppData\Roaming\Python\Python37\site-packages\rl_agents\agents\common\utils.py", line 84, in choose_device
    preferred_device = least_used_device()
  File "C:\Users\user1\AppData\Roaming\Python\Python37\site-packages\rl_agents\agents\common\utils.py", line 75, in least_used_device
    memory_map = get_gpu_memory_map()
  File "C:\Users\user1\AppData\Roaming\Python\Python37\site-packages\rl_agents\agents\common\utils.py", line 66, in get_gpu_memory_map
    result = check_output(['nvidia-smi', '--query-gpu=memory.used', '--format=csv,nounits,noheader'])
  File "D:\Anaconda\lib\subprocess.py", line 389, in check_output
    **kwargs).stdout
  File "D:\Anaconda\lib\subprocess.py", line 466, in run
    with Popen(*popenargs, **kwargs) as process:
  File "D:\Anaconda\lib\subprocess.py", line 769, in __init__
    restore_signals, start_new_session)
  File "D:\Anaconda\lib\subprocess.py", line 1172, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] 系统找不到指定的文件。

When I run the highway-env in the terminal, the problem is：
(base) C:\Users\user1\RL\scripts>python experiments.py evaluate configs/HighwayEnv/env.json configs/HighwayEnv/agents/DQNAgent/dqn.json --train --episodes=200
pygame 1.9.6
Hello from the pygame community. https://www.pygame.org/contribute.html
INFO: Making new env: highway-v0
[INFO] NumExpr defaulting to 8 threads.
Traceback (most recent call last):
  File "experiments.py", line 148, in <module>
    main()
  File "experiments.py", line 43, in main
    evaluate(opts['<environment>'], opts['<agent>'], opts)
  File "experiments.py", line 60, in evaluate
    agent = load_agent(agent_config, env)
  File "C:\Users\user1\AppData\Roaming\Python\Python37\site-packages\rl_agents\agents\common\factory.py", line 41, in load_agent
    return agent_factory(env, agent_config)
  File "C:\Users\user1\AppData\Roaming\Python\Python37\site-packages\rl_agents\agents\common\factory.py", line 24, in agent_factory
    agent = agent_class(environment, config)
  File "C:\Users\user1\AppData\Roaming\Python\Python37\site-packages\rl_agents\agents\deep_q_network\pytorch.py", line 22, in __init__
    self.device = choose_device(self.config["device"])
  File "C:\Users\user1\AppData\Roaming\Python\Python37\site-packages\rl_agents\agents\common\utils.py", line 84, in choose_device
    preferred_device = least_used_device()
  File "C:\Users\user1\AppData\Roaming\Python\Python37\site-packages\rl_agents\agents\common\utils.py", line 75, in least_used_device
    memory_map = get_gpu_memory_map()
  File "C:\Users\user1\AppData\Roaming\Python\Python37\site-packages\rl_agents\agents\common\utils.py", line 66, in get_gpu_memory_map
    result = check_output(['nvidia-smi', '--query-gpu=memory.used', '--format=csv,nounits,noheader'])
  File "D:\Anaconda\lib\subprocess.py", line 389, in check_output
    **kwargs).stdout
  File "D:\Anaconda\lib\subprocess.py", line 466, in run
    with Popen(*popenargs, **kwargs) as process:
  File "D:\Anaconda\lib\subprocess.py", line 769, in __init__
    restore_signals, start_new_session)
  File "D:\Anaconda\lib\subprocess.py", line 1172, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] 系统找不到指定的文件。

**Comment by eleurent** [comment]
Hi @narutoten520,

Hmm, I think the error you get is related to the
```
check_output(['nvidia-smi', '--query-gpu=memory.used', '--format=csv,nounits,noheader'])
```
that is used in rl-agents to find the GPU with least used memory.

Maybe you don't have the `nvidia-smi` utility installed?
I will add a fix when it is the case: the program should fallback to CPU.

Thanks for the feedback!

**Comment by eleurent** [comment]
There you go! You should update your installation of [rl-agents](https://github.com/eleurent/rl-agents) with the latest (master) version.

**Comment by narutoten520** [comment]
Many thanks for your immediate responses. I will try to update the rl-agests and run it. Thanks for your work.

**Comment by narutoten520** [comment]
@eleurent Hi eleurent, with your help, now I can train and test the Highway-env with DQN. However, when I follow your instruction to see the results with tensorboard,  it shows following error:

(base) C:\Users\user1\rl-agents\scripts>tensorboard --logdir out/HighwayEnv/DQNAgent/run_20200619-114451_13448
TensorBoard 1.15.0 at http://DESKTOP-H6H55DR:6006/ (Press CTRL+C to quit)
W0619 11:45:42.685292 19736 core_plugin.py:185] Unable to get first event timestamp for run .: No event timestamp could be found.


![image](https://user-images.githubusercontent.com/40506882/85095190-4c2f7700-b223-11ea-881d-4dcf41d35313.png)

I am not sure my training process is right or not because it finishes with only one second with 5000 episodes (I am wondering there may no results stored in run-files ). So I attach the run-files to let you check. Thanks for your help. Best!


[run_20200619-114221_19036.zip](https://github.com/eleurent/highway-env/files/4802373/run_20200619-114221_19036.zip)
