### ISSUE TITLE
Some questions about recent learning

### ISSUE THREAD

**Issue by narutoten520** [eleurent/highway-env#92]
Hello @eleurent , sorry for trouble you again. I want to ask some questions about my recent learning about this work.

1. I find the reward and score of each episode are related to the duration (The duration is the maximum value). Could you please explain to me what's the relationship between them? Because the reward is defined as the sum of three terms, why is it limited by duration?

2. The factor of the collision, highspeed and right lane are -1, 0.4 and 0.1.  (in highway-env). Are they the optimal values? Because whey I change them, the performance becomes worse.

3. I find a continuous space of control actions in the envs of rl-agents. So can I use the DDPG to train it? If so, could you please guide me how to add the DDPG algorithm？

4. Recently, I want to write a paper about this decision-making problem. I will cite your work, furthermore, I want to add you as the co-author to thank your contribution. Does that work for you?

**Comment by eleurent** [comment]
Hey, sure no problem!
1. at each step the reward is between 0 and 1. If the episode is of length H, the sum of rewards is between 0 and H. (in rl-agents I use the term 'score' to refer to total reward)
2. the factors were chosen manually, so they are not "optimal". When you say the performance becomes worse, you mean the qualitative behaviour? (Because I don't think you can compare the total rewards obtained with two different reward functions.)
3. Sure, you can use for example the implementations of openai/baselines (try [this script](https://github.com/eleurent/highway-env/blob/master/scripts/run_baselines.py), with DDPG+HER) and stable_baselines (you can modify this notebook to use DDPG instead of SAC (https://colab.research.google.com/github/eleurent/highway-env/blob/master/scripts/parking_her.ipynb).
4. That is very kind of you (!), but I do not think you should add me as a co-author if I do not contribute to the work directly. I would be grateful for a citation, though :)

**Comment by narutoten520** [comment]
Hello @eleurent , many thanks for your hard work to release the first stable version of this environment. I have upgraded the highway-env and rl-agents on my PC today. When I run the multi-agents with DQN in HighwayEnv or IntersectionEnv, some issues happen. Please help me to find the problems, thanks a lot.

1. Run code: python experiments.py evaluate configs/HighwayEnv/env_multi_agent.json configs/HighwayEnv/agents/DQNAgent/dqn.json --train --episodes=40 --name-from-config

INFO: Making new env: highway-v0
Traceback (most recent call last):
  File "experiments.py", line 148, in <module>
    main()
  File "experiments.py", line 43, in main
    evaluate(opts['<environment>'], opts['<agent>'], opts)
  File "experiments.py", line 59, in evaluate
    env = load_environment(environment_config)
  File "C:\Users\tengl\AppData\Roaming\Python\Python37\site-packages\rl_agents\agents\common\factory.py", line 91, in load_environment
    env.reset()
  File "C:\Users\tengl\AppData\Roaming\Python\Python37\site-packages\highway_env\envs\highway_env.py", line 48, in reset
    super().reset()
  File "C:\Users\tengl\AppData\Roaming\Python\Python37\site-packages\highway_env\envs\common\abstract.py", line 149, in reset
    self.define_spaces()
  File "C:\Users\tengl\AppData\Roaming\Python\Python37\site-packages\highway_env\envs\common\abstract.py", line 109, in define_spaces
    self.observation_type = observation_factory(self, self.config["observation"])
  File "C:\Users\tengl\AppData\Roaming\Python\Python37\site-packages\highway_env\envs\common\observation.py", line 351, in observation_factory
    raise ValueError("Unknown observation type")
ValueError: Unknown observation type

2. Run Code: python experiments.py evaluate configs/IntersectionEnv/env_multi_agent.json configs/IntersectionEnv/agents/DQNAgent/baseline.json --train --episodes=40 --name-from-config

INFO: Making new env: intersection-multi-agent-v0
import_module highway_env
Traceback (most recent call last):
  File "D:\Anacoda\lib\site-packages\gym\envs\registration.py", line 121, in spec
    return self.env_specs[id]
KeyError: 'intersection-multi-agent-v0'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\tengl\AppData\Roaming\Python\Python37\site-packages\rl_agents\agents\common\factory.py", line 75, in load_environment
    env = gym.make(env_config['id'])
  File "D:\Anacoda\lib\site-packages\gym\envs\registration.py", line 145, in make
    return registry.make(id, **kwargs)
  File "D:\Anacoda\lib\site-packages\gym\envs\registration.py", line 89, in make
    spec = self.spec(path)
  File "D:\Anacoda\lib\site-packages\gym\envs\registration.py", line 131, in spec
    raise error.UnregisteredEnv('No registered env with id: {}'.format(id))
gym.error.UnregisteredEnv: No registered env with id: intersection-multi-agent-v0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "experiments.py", line 148, in <module>
    main()
  File "experiments.py", line 43, in main
    evaluate(opts['<environment>'], opts['<agent>'], opts)
  File "experiments.py", line 59, in evaluate
    env = load_environment(environment_config)
  File "C:\Users\tengl\AppData\Roaming\Python\Python37\site-packages\rl_agents\agents\common\factory.py", line 85, in load_environment
    env_config['id']))
gym.error.UnregisteredEnv: Environment intersection-multi-agent-v0 not registered. The environment module should be specified by the "import_module" key of the environment configuration

**Comment by eleurent** [comment]
Hey, sorry about that. The `env_multi_agent.json` env config requires the new multi-agent feature, which will be merged very soon: https://github.com/eleurent/highway-env/pull/102

**Comment by eleurent** [comment]
I guess I should have a stable version of `rl-agents` as well, so that this does not happen again.

**Comment by eleurent** [comment]
The feature has been merged, everything should work properly now.
